@extends('layouts.app')
@section('title', 'Audit Trail | HisebGhor')
@section('content')
<div class="page-title">
    <div>
        <span class="page-label">Audit Trail</span>
        <h2>System Activity Log</h2>
        <p>Track sensitive setup, rule, voucher, user, permission, approval, and reversal changes.</p>
    </div>
</div>

<div class="audit-readonly-banner" style="margin-bottom:16px">
    <span>🔒</span>
    <div>
        <strong>Read-only compliance log.</strong>
        Audit records are generated by the backend and cannot be edited from the application UI. Use filters for module/action review during handover or audit checks.
    </div>
</div>

<div class="card toolbar" style="margin-bottom:16px">
    <form method="GET" style="display:contents">
        <div>
            <label>Module</label>
            <input name="module" value="{{ $filters['module'] ?? '' }}" placeholder="Example: VoucherHeader">
        </div>

        <div>
            <label>Action</label>
            <input name="event" value="{{ $filters['event'] ?? '' }}" placeholder="Example: updated">
        </div>

        <div>
            <label>Route</label>
            <input name="route" value="{{ $filters['route'] ?? '' }}" placeholder="Route name">
        </div>

        <button class="btn-primary" type="submit">Filter</button>
        <a class="btn-ghost" href="{{ route('audit-trail.index') }}">Reset</a>
    </form>
</div>

<div class="card table-card">
    <div class="table-wrap">
        <table>
            <thead>
                <tr>
                    <th>Time</th>
                    <th>Module</th>
                    <th>Action</th>
                    <th>Record</th>
                    <th>User</th>
                    <th>Route</th>
                    <th>IP</th>
                    <th>Change Summary</th>
                </tr>
            </thead>
            <tbody>
                @forelse($logs as $log)
                    <tr>
                        <td>{{ optional($log->created_at)->format('d M Y h:i A') }}</td>
                        <td>{{ $log->module ?? class_basename($log->auditable_type) }}</td>
                        <td><span class="badge badge-neutral">{{ $log->action ?? $log->event }}</span></td>
                        <td>#{{ $log->auditable_id }}</td>
                        <td>{{ $log->user?->name ?? 'System' }}</td>
                        <td><small>{{ $log->route_name ?? '-' }}</small></td>
                        <td><small>{{ $log->ip_address ?? '-' }}</small></td>
                        <td><small>{{ \Illuminate\Support\Str::limit(json_encode($log->new_values ?: $log->old_values ?: $log->metadata), 180) }}</small></td>
                    </tr>
                @empty
                    <tr data-empty="true"><td colspan="8" class="muted">No audit log entries found.</td></tr>
                @endforelse
            </tbody>
        </table>
    </div>
    <div class="table-footer">{{ $logs->links() }}</div>
</div>
@endsection
