@php
    use App\Services\Setup\SetupProgressService;
    use Illuminate\Support\Facades\Route;

    $currentUser = auth()->user();
    $progressService = app(SetupProgressService::class);

    $current = (int) ($current ?? 1);

    $steps = collect($progressService->steps())
        ->map(function ($step) {
            $route = $step['route'];

            if (! Route::has($route) && isset($step['legacy_route']) && Route::has($step['legacy_route'])) {
                $route = $step['legacy_route'];
            }

            $step['resolved_route'] = $route;

            return $step;
        })
        ->filter(fn ($step) => Route::has($step['resolved_route']) && ($currentUser?->canViewRoute($step['resolved_route']) ?? false))
        ->all();

    $total = max(1, $progressService->totalCount($steps));
    $completed = $progressService->completedCount($steps);
    $percent = $progressService->percent($steps);
@endphp

@if(count($steps) > 0)
<div class="card setup-progress-horizontal" aria-label="Setup Progress">
    <div class="setup-progress-head">
        <div>
            <span class="section-label">Setup Progress</span>
            <h3>{{ $percent }}% Complete</h3>
        </div>

        <div class="setup-progress-count">
            Completed {{ $completed }} of {{ $total }}
        </div>
    </div>

    <div class="progress-track" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="{{ $percent }}">
        <div class="progress-fill" style="width: {{ $percent }}%"></div>
    </div>

    <div class="setup-progress-steps">
        @foreach($steps as $number => $step)
            @php
                $label = $step['label'];
                $route = $step['resolved_route'];
                $url = route($route);
                $isCompleted = (bool) ($step['completed'] ?? false);
                $isAutoGenerated = (bool) ($step['auto_generated'] ?? false);
                $isCurrent = $number === $current;
                $state = $isCompleted ? 'done' : ($isCurrent ? 'current' : 'pending');
                $status = $isAutoGenerated
                    ? ($isCompleted ? 'Auto Generated' : 'Auto Generated after source setup')
                    : ($isCompleted ? 'Completed' : ($isCurrent ? 'In Progress' : 'Pending'));
            @endphp

            <a
                href="{{ $url }}"
                class="setup-progress-step {{ $state }}"
                @if($isCurrent) aria-current="page" @endif
                title="Go to {{ $label }}"
            >
                <div class="setup-progress-dot">
                    {{ $isCompleted ? '✓' : $number }}
                </div>

                <div class="setup-progress-copy">
                    <strong>{{ $label }}</strong>
                    <span>{{ $status }}</span>
                </div>
            </a>
        @endforeach
    </div>
</div>
@endif
