<?php
    use App\Services\Setup\SetupProgressService;
    use Illuminate\Support\Facades\Route;

    $currentUser = auth()->user();
    $progressService = app(SetupProgressService::class);

    $current = (int) ($current ?? 1);

    $steps = collect($progressService->steps())
        ->map(function ($step) {
            $route = $step['route'];

            if (! Route::has($route) && isset($step['legacy_route']) && Route::has($step['legacy_route'])) {
                $route = $step['legacy_route'];
            }

            $step['resolved_route'] = $route;

            return $step;
        })
        ->filter(fn ($step) => Route::has($step['resolved_route']) && ($currentUser?->canViewRoute($step['resolved_route']) ?? false))
        ->all();

    $total = max(1, $progressService->totalCount($steps));
    $completed = $progressService->completedCount($steps);
    $percent = $progressService->percent($steps);
?>

<?php if(count($steps) > 0): ?>
<div class="card setup-progress-horizontal" aria-label="Setup Progress">
    <div class="setup-progress-head">
        <div>
            <span class="section-label">Setup Progress</span>
            <h3><?php echo e($percent); ?>% Complete</h3>
        </div>

        <div class="setup-progress-count">
            Completed <?php echo e($completed); ?> of <?php echo e($total); ?>

        </div>
    </div>

    <div class="progress-track" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="<?php echo e($percent); ?>">
        <div class="progress-fill" style="width: <?php echo e($percent); ?>%"></div>
    </div>

    <div class="setup-progress-steps">
        <?php $__currentLoopData = $steps; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $number => $step): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
            <?php
                $label = $step['label'];
                $route = $step['resolved_route'];
                $url = route($route);
                $isCompleted = (bool) ($step['completed'] ?? false);
                $isAutoGenerated = (bool) ($step['auto_generated'] ?? false);
                $isCurrent = $number === $current;
                $state = $isCompleted ? 'done' : ($isCurrent ? 'current' : 'pending');
                $status = $isAutoGenerated
                    ? ($isCompleted ? 'Auto Generated' : 'Auto Generated after source setup')
                    : ($isCompleted ? 'Completed' : ($isCurrent ? 'In Progress' : 'Pending'));
            ?>

            <a
                href="<?php echo e($url); ?>"
                class="setup-progress-step <?php echo e($state); ?>"
                <?php if($isCurrent): ?> aria-current="page" <?php endif; ?>
                title="Go to <?php echo e($label); ?>"
            >
                <div class="setup-progress-dot">
                    <?php echo e($isCompleted ? '✓' : $number); ?>

                </div>

                <div class="setup-progress-copy">
                    <strong><?php echo e($label); ?></strong>
                    <span><?php echo e($status); ?></span>
                </div>
            </a>
        <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
    </div>
</div>
<?php endif; ?>
<?php /**PATH /Applications/XAMPP/xamppfiles/htdocs/laravel/project_work/resources/views/partials/setup-progress.blade.php ENDPATH**/ ?>