<style>
  :root{
    --green:<?php echo e(data_get($landing, 'theme.green', '#00a86b')); ?>;
    --green-dark:<?php echo e(data_get($landing, 'theme.green_dark', '#087a52')); ?>;
    --green-soft:<?php echo e(data_get($landing, 'theme.green_soft', '#e9fff5')); ?>;
    --red:#ef4444;
    --blue:<?php echo e(data_get($landing, 'theme.blue', '#2563eb')); ?>;
    --blue-soft:#eef4ff;
    --gold:<?php echo e(data_get($landing, 'theme.gold', '#f59e0b')); ?>;
    --ink:<?php echo e(data_get($landing, 'theme.ink', '#101828')); ?>;
    --muted:<?php echo e(data_get($landing, 'theme.muted', '#667085')); ?>;
    --line:#e5e7eb;
    --bg:<?php echo e(data_get($landing, 'theme.bg', '#f8fafc')); ?>;
    --white:#fff;
    --shadow:0 20px 50px rgba(16,24,40,.08);
    --radius:24px;
  }
  *{box-sizing:border-box}
  html{scroll-behavior:smooth}
  body{margin:0;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",Noto Sans Bengali,sans-serif;background:var(--bg);color:var(--ink)}
  a{text-decoration:none;color:inherit}
  .container{width:min(1180px,calc(100% - 36px));margin:0 auto}
  .preview-banner{position:sticky;top:0;z-index:40;background:#111827;color:#fff;text-align:center;padding:9px 14px;font-weight:900;font-size:13px}
  .topbar{position:sticky;top:0;z-index:20;background:rgba(255,255,255,.88);backdrop-filter:blur(16px);border-bottom:1px solid rgba(229,231,235,.8)}
  .preview-banner + .topbar{top:36px}
  .nav{height:76px;display:flex;align-items:center;justify-content:space-between;gap:20px}
  .brand{display:flex;align-items:center;gap:12px}.brand-image-only{min-width:0}.brand-logo-full{display:block;width:auto;max-width:210px;height:52px;object-fit:contain;object-position:left center}.footer-brand-logo-full{max-width:240px;height:58px;filter:none}.brand-fallback-mark{width:44px;height:44px;border-radius:15px;background:linear-gradient(135deg,var(--green),#16a34a);display:grid;place-items:center;color:#fff;font-weight:900;font-size:22px;box-shadow:0 14px 25px rgba(0,168,107,.24);overflow:hidden}.brand-fallback-text strong{font-size:22px;letter-spacing:-.03em}.brand-fallback-text span{display:block;font-size:12px;color:var(--muted);margin-top:2px}.logo{width:44px;height:44px;border-radius:15px;background:linear-gradient(135deg,var(--green),#16a34a);display:grid;place-items:center;color:#fff;font-weight:900;font-size:22px;box-shadow:0 14px 25px rgba(0,168,107,.24);overflow:hidden}.logo.has-image{background:#fff;padding:0}.logo img{display:block;width:100%;height:100%;object-fit:cover}.brand strong{font-size:22px;letter-spacing:-.03em}.brand span{display:block;font-size:12px;color:var(--muted);margin-top:2px}
  .navlinks{display:flex;align-items:center;gap:24px;color:#475467;font-size:14px;font-weight:700}.navlinks a:hover{color:var(--green)}
  .actions{display:flex;gap:10px;align-items:center}.lang-toggle{height:42px;border:1px solid var(--line);background:#fff;border-radius:999px;padding:4px;display:flex;gap:4px}
  .lang-toggle button{border:0;background:transparent;border-radius:999px;padding:8px 12px;font-weight:800;color:#475467;cursor:pointer}.lang-toggle button.active{background:var(--green);color:#fff}
  .btn{display:inline-flex;align-items:center;justify-content:center;gap:8px;border:0;border-radius:999px;padding:13px 19px;font-weight:900;cursor:pointer;transition:.18s ease}.btn:hover{transform:translateY(-1px)}
  .btn-primary{background:var(--green);color:#fff;box-shadow:0 14px 28px rgba(0,168,107,.24)}.btn-outline{background:#fff;color:var(--green-dark);border:1px solid #b7ebd0}.btn-dark{background:#111827;color:#fff}
  .mobile-menu-toggle{display:none;width:44px;height:44px;border:1px solid var(--line);border-radius:14px;background:#fff;align-items:center;justify-content:center;flex-direction:column;gap:5px;cursor:pointer;box-shadow:0 8px 18px rgba(16,24,40,.06)}
  .mobile-menu-toggle span{display:block;width:19px;height:2px;border-radius:999px;background:#344054;transition:.16s ease}.mobile-menu-toggle.open span:nth-child(1){transform:translateY(7px) rotate(45deg)}.mobile-menu-toggle.open span:nth-child(2){opacity:0}.mobile-menu-toggle.open span:nth-child(3){transform:translateY(-7px) rotate(-45deg)}
  .mobile-nav-panel{display:none;border-top:1px solid var(--line);background:rgba(255,255,255,.98);box-shadow:0 22px 34px rgba(16,24,40,.08)}.mobile-nav-panel.open{display:block}.mobile-nav-inner{padding:14px 0 18px;display:grid;gap:8px}.mobile-nav-inner>a{display:flex;align-items:center;min-height:44px;border-radius:14px;padding:11px 14px;background:#f8fafc;color:#344054;font-weight:850;border:1px solid #eef2f7}.mobile-nav-inner>a:hover{background:var(--green-soft);color:var(--green-dark)}.mobile-nav-actions{display:grid;gap:10px;margin-top:6px}.mobile-nav-actions .btn{width:100%}
  .hero{position:relative;overflow:hidden;background:radial-gradient(circle at top left,#dcfce7 0,#f8fafc 34%,#fff 100%);padding:72px 0 54px}.hero:before{content:"";position:absolute;right:-120px;top:40px;width:360px;height:360px;border-radius:50%;background:rgba(0,168,107,.09)}
  .hero-grid{position:relative;display:grid;grid-template-columns:1.05fr .95fr;gap:42px;align-items:center}.eyebrow{display:inline-flex;align-items:center;gap:8px;border:1px solid #bbf7d0;background:#f0fdf4;color:#067647;border-radius:999px;padding:8px 12px;font-size:13px;font-weight:850;margin-bottom:18px}
  .hero h1{margin:0;font-size:58px;line-height:1.02;letter-spacing:-.06em}.hero h1 span{color:var(--green-dark)}.hero p{margin:20px 0 0;color:#475467;font-size:19px;line-height:1.65;max-width:650px}.hero-buttons{display:flex;gap:12px;flex-wrap:wrap;margin-top:28px}.trust-row{display:flex;gap:18px;flex-wrap:wrap;margin-top:30px}.trust{display:flex;gap:9px;align-items:center;color:#344054;font-size:14px;font-weight:750}.tick{width:22px;height:22px;border-radius:50%;display:grid;place-items:center;background:var(--green-soft);color:var(--green);font-weight:900;flex:0 0 auto}
  .hero-card{background:#fff;border:1px solid var(--line);border-radius:30px;box-shadow:var(--shadow);padding:18px}.browser-bar{display:flex;align-items:center;gap:8px;border-bottom:1px solid var(--line);padding:0 0 14px}.dot{width:10px;height:10px;border-radius:50%;background:#d0d5dd}.dot:nth-child(1){background:#f87171}.dot:nth-child(2){background:#fbbf24}.dot:nth-child(3){background:#34d399}.mock{padding:18px;background:#fbfcfd;border-radius:20px;margin-top:14px}.mock-top{display:flex;justify-content:space-between;align-items:center;margin-bottom:16px}.mock-title strong{display:block;font-size:18px}.mock-title span{color:var(--muted);font-size:12px}.mock-chip{background:var(--green-soft);color:var(--green-dark);padding:7px 10px;border-radius:999px;font-size:12px;font-weight:900}.mock-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-bottom:14px}.mock-stat{background:#fff;border:1px solid var(--line);border-radius:14px;padding:12px}.mock-stat span{display:block;color:var(--muted);font-size:11px}.mock-stat strong{display:block;margin-top:6px;font-size:16px}.mock-table{background:#fff;border:1px solid var(--line);border-radius:16px;overflow:hidden}.mock-row{display:grid;grid-template-columns:1fr .7fr .7fr;gap:10px;padding:12px;border-bottom:1px solid #edf0f3;font-size:12px}.mock-row:last-child{border-bottom:0}.mock-row.head{background:#f8fafc;color:#475467;font-weight:900}.green{color:#067647}.red{color:#dc2626}.dashboard-preview{padding:0;background:transparent}.hero-card.hero-image-only-card{background:#fff;border:1px solid var(--line);border-radius:30px;box-shadow:var(--shadow);padding:0;overflow:hidden}.dashboard-preview-image{display:block;width:100%;aspect-ratio:16/10;object-fit:cover;border-radius:30px;border:0;background:#fff}.dashboard-preview-image-only{border-radius:30px}.dashboard-preview-placeholder{display:grid;place-items:center;text-align:center;min-height:260px;border:1px dashed #cbd5e1;border-radius:18px;background:linear-gradient(135deg,#fff,#f1f5f9);color:#475467;font-weight:900}.dashboard-preview-placeholder small{display:block;margin-top:8px;color:var(--muted);font-weight:700}
  .section{padding:78px 0}.section-title{text-align:center;max-width:760px;margin:0 auto 38px}.section-title .mini{color:var(--green);font-weight:900;font-size:14px;margin-bottom:10px}.section-title h2{margin:0;font-size:40px;line-height:1.15;letter-spacing:-.04em}.section-title p{margin:14px 0 0;color:var(--muted);font-size:17px;line-height:1.65}
  .grid-3{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.feature-card,.simple-card,.package,.testimonial,.faq-item,.contact-card{background:#fff;border:1px solid var(--line);border-radius:var(--radius);box-shadow:0 10px 28px rgba(16,24,40,.05)}.feature-card{padding:24px}.icon{width:50px;height:50px;border-radius:16px;display:grid;place-items:center;background:var(--green-soft);color:var(--green);font-size:24px;margin-bottom:18px}.feature-card h3,.simple-card h3{margin:0 0 9px;font-size:20px}.feature-card p,.simple-card p{margin:0;color:var(--muted);line-height:1.6}
  .for-grid{display:grid;grid-template-columns:.9fr 1.1fr;gap:24px;align-items:stretch}.simple-card{padding:26px}.audience-list{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}.audience{background:#fff;border:1px solid var(--line);border-radius:18px;padding:18px;display:flex;gap:12px;align-items:flex-start}.audience b{display:block;margin-bottom:4px}.audience span{color:var(--muted);font-size:14px;line-height:1.45}
  .screens{background:#0f172a;color:#fff;overflow:hidden}.screens .section-title p,.screens .section-title .mini{color:#d1fae5}.screen-grid{display:grid;grid-template-columns:1fr 1fr;gap:22px}.screen-card{background:rgba(255,255,255,.08);border:1px solid rgba(255,255,255,.14);border-radius:26px;padding:18px}.screen-img{background:#fff;border-radius:20px;overflow:hidden;color:#111827;aspect-ratio:3/1;min-height:0}.screen-img.has-uploaded-image{position:relative;background:#fff;display:block}.screen-card-image{display:block;width:100%;height:100%;object-fit:cover;object-position:center}.screen-head{height:46px;display:flex;gap:8px;align-items:center;padding:0 14px;border-bottom:1px solid var(--line)}.screen-body{padding:16px}.highlight{display:inline-flex;background:#ecfdf3;color:#067647;border:1px solid #bbf7d0;border-radius:999px;padding:6px 9px;font-weight:900;font-size:12px;margin:4px}.screen-lines{display:grid;gap:10px;margin-top:12px}.line{height:12px;border-radius:999px;background:#e5e7eb}.line.w70{width:70%}.line.w45{width:45%}.screen-card h3{margin:16px 4px 6px}.screen-card p{margin:0 4px 4px;color:#cbd5e1;line-height:1.55}
  .packages{display:grid;grid-template-columns:repeat(3,1fr);gap:20px}.package{padding:26px;position:relative}.package.popular{border:2px solid var(--green);transform:translateY(-8px)}.popular-tag{position:absolute;top:18px;right:18px;background:var(--green);color:#fff;border-radius:999px;padding:6px 10px;font-size:12px;font-weight:900}.package h3{margin:0 0 8px;font-size:22px}.package p{margin:0;color:var(--muted);line-height:1.55}.price{margin:22px 0;font-size:36px;font-weight:950;letter-spacing:-.05em}.price small{font-size:14px;color:var(--muted);font-weight:700}.package ul{list-style:none;padding:0;margin:0 0 24px;display:grid;gap:11px;color:#344054}.package li:before{content:"✓";color:var(--green);font-weight:900;margin-right:9px}
  .testimonials{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.testimonial{padding:24px}.quote{font-size:34px;color:var(--green);line-height:1}.testimonial p{color:#475467;line-height:1.65}.person{display:flex;gap:12px;align-items:center;margin-top:18px}.person-avatar{width:42px;height:42px;border-radius:50%;background:var(--green-soft);color:var(--green);display:grid;place-items:center;font-weight:900}.person strong{display:block}.person span{color:var(--muted);font-size:13px}
  .faq{display:grid;gap:12px;max-width:850px;margin:0 auto}.faq-item{overflow:hidden}.faq-q{padding:18px 20px;display:flex;justify-content:space-between;gap:16px;align-items:center;cursor:pointer;font-weight:900}.faq-a{display:none;padding:0 20px 18px;color:var(--muted);line-height:1.65}.faq-item.open .faq-a{display:block}.contact{background:linear-gradient(135deg,#ecfdf5,#eff6ff)}.contact-grid{display:grid;grid-template-columns:.9fr 1.1fr;gap:22px}.contact-card{padding:28px}.contact-card h3{margin:0 0 12px;font-size:26px}.contact-card p{color:var(--muted);line-height:1.65}.contact-methods{display:grid;gap:12px;margin:20px 0}.contact-method{display:flex;gap:12px;align-items:center;background:#f8fafc;border:1px solid var(--line);border-radius:16px;padding:14px;text-decoration:none;color:inherit;transition:.15s ease}.contact-method:hover{border-color:#bbf7d0;box-shadow:0 10px 25px rgba(0,168,107,.10);transform:translateY(-1px)}.contact-method b{display:block}.contact-method span{color:var(--muted);font-size:14px}.form{display:grid;gap:12px}input,textarea{font-family:inherit}.form input,.form textarea{width:100%;border:1px solid #d8dee9;border-radius:14px;padding:14px;background:#fff;font-size:15px}.form textarea{min-height:116px;resize:vertical}.form-status{display:none;border-radius:14px;padding:12px 14px;font-weight:800;background:#ecfdf3;color:#067647}.form-status.error{background:#fef2f2;color:#b42318}
  .footer{background:#0b1220;color:#cbd5e1;padding:36px 0}.footer-grid{display:flex;justify-content:space-between;gap:22px;align-items:flex-start}.footer strong{color:#fff}.footer p{margin:8px 0 0;color:#94a3b8;line-height:1.6}.footer-links{display:flex;gap:18px;flex-wrap:wrap}.hidden{display:none!important}
  @media(max-width:1000px){.navlinks{display:none}.mobile-menu-toggle{display:flex}.hero-grid,.for-grid,.contact-grid{grid-template-columns:1fr}.hero h1{font-size:46px}.grid-3,.packages,.testimonials,.screen-grid{grid-template-columns:1fr 1fr}}
  @media(max-width:720px){.mobile-nav-actions{grid-template-columns:1fr}.container{width:min(100% - 24px,1180px)}.hero{padding:46px 0}.hero h1{font-size:38px}.section{padding:54px 0}.section-title h2{font-size:32px}.grid-3,.packages,.testimonials,.screen-grid,.audience-list{grid-template-columns:1fr}.package.popular{transform:none}.footer-grid{display:grid}.actions .btn-primary{display:none}.mock-stats{grid-template-columns:1fr}.dashboard-preview-placeholder{min-height:210px}.nav{height:68px}.brand strong{font-size:19px}.brand-logo-full{max-width:170px;height:46px}.actions .btn-outline{display:none}}
</style>
<?php /**PATH /Applications/XAMPP/xamppfiles/htdocs/laravel/project_work/resources/views/landing/components/styles.blade.php ENDPATH**/ ?>