<?php

return [
    'roles' => [
        'Super Admin' => [
            'level' => 1,
            'description' => 'System owner with full software and company control.',
            'protected' => true,
        ],
        'Admin' => [
            'level' => 2,
            'description' => 'Company administrator with full company-level control except Super Admin control.',
            'protected' => false,
        ],
        'Company Admin' => [
            'level' => 2,
            'description' => 'Company administrator with setup, users, and company-level configuration access.',
            'protected' => false,
        ],
        'Finance Manager' => [
            'level' => 3,
            'description' => 'Supervises accounting activities, approvals, ledgers, reports, and period review.',
            'protected' => false,
        ],
        'Approver' => [
            'level' => 3,
            'description' => 'Reviews and approves/rejects financial transactions.',
            'protected' => false,
        ],
        'Accountant' => [
            'level' => 4,
            'description' => 'Creates and maintains daily accounting entries, ledgers, and basic reports.',
            'protected' => false,
        ],
        'Cashier' => [
            'level' => 5,
            'description' => 'Handles cash/bank receipt, payment, petty cash, and daily cash activity.',
            'protected' => false,
        ],
        'Sales User' => [
            'level' => 5,
            'description' => 'Creates sales/customer transactions and receives customer payments.',
            'protected' => false,
        ],
        'Purchase User' => [
            'level' => 5,
            'description' => 'Creates purchase/supplier transactions and supplier payments.',
            'protected' => false,
        ],
        'Inventory / Store User' => [
            'level' => 5,
            'description' => 'Handles inventory/store activity where the inventory module is enabled.',
            'protected' => false,
        ],
        'Branch User' => [
            'level' => 5,
            'description' => 'Operates only inside assigned branch and assigned feature scope.',
            'protected' => false,
        ],
        'Data Entry Operator' => [
            'level' => 6,
            'description' => 'Creates draft entries only; no approval, delete, or final posting authority.',
            'protected' => false,
        ],
        'Auditor' => [
            'level' => 6,
            'description' => 'Read-only reviewer for vouchers, ledgers, reports, history, and audit trail.',
            'protected' => false,
        ],
        'Management Viewer / Report Viewer' => [
            'level' => 7,
            'description' => 'Read-only viewer for dashboard and management reports.',
            'protected' => false,
        ],
        'Viewer' => [
            'level' => 7,
            'description' => 'Read-only access to allowed dashboard and report views.',
            'protected' => false,
        ],
        'Support Admin' => [
            'level' => 8,
            'description' => 'Controlled support access without silent financial edit permission.',
            'protected' => false,
        ],
    ],

    'permissions' => [
        'dashboard.view' => 'View Dashboard',
        'company.view' => 'View Company Setup',
        'company.manage' => 'Manage Company Setup',
        'master-data.view' => 'View Master Data',
        'master-data.manage' => 'Manage Master Data',
        'chart-of-accounts.view' => 'View Chart of Accounts',
        'chart-of-accounts.manage' => 'Manage Chart of Accounts',
        'cash-bank.view' => 'View Cash / Bank Setup',
        'cash-bank.manage' => 'Manage Cash / Bank Setup',
        'parties.view' => 'View Party / Person Setup',
        'parties.manage' => 'Manage Party / Person Setup',
        'transaction-heads.view' => 'View Transaction Heads',
        'transaction-heads.manage' => 'Manage Transaction Heads',
        'ledger-mapping.view' => 'View Accounting Rules Setup',
        'ledger-mapping.manage' => 'Manage Accounting Rules Setup',
        'opening-balances.view' => 'View Opening Balance Setup',
        'opening-balances.manage' => 'Manage Opening Balance Setup',
        'voucher-numbering.view' => 'View Voucher Numbering',
        'voucher-numbering.manage' => 'Manage Voucher Numbering',
        'transactions.view' => 'View Voucher Entry',
        'transactions.create' => 'Create Voucher Entry',
        'transactions.edit' => 'Edit Voucher Entry',
        'transactions.draft' => 'Create Draft Voucher Only',
        'transactions.payment.create' => 'Create Payment Entry',
        'transactions.receipt.create' => 'Create Receipt Entry',
        'transactions.journal.create' => 'Create Journal Entry',
        'transactions.sales.create' => 'Create Sales Related Entry',
        'transactions.purchase.create' => 'Create Purchase Related Entry',
        'transactions.reverse' => 'Reverse / Cancel Transaction',
        'sales-invoices.view' => 'View Sales Invoice',
        'sales-invoices.manage' => 'Manage Sales Invoice',
        'purchase-bills.view' => 'View Purchase Bill',
        'purchase-bills.manage' => 'Manage Purchase Bill',
        'customer-ledgers.view' => 'View Customer Ledger',
        'supplier-ledgers.view' => 'View Supplier Ledger',
        'due-management.view' => 'View Due Management',
        'due-management.manage' => 'Manage Due Payment / Collection',
        'advance-management.view' => 'View Advance Management',
        'advance-management.manage' => 'Manage Advance Entry / Adjustment',
        'ledger-report.view' => 'View Ledger Report',
        'cash-bank-book.view' => 'View Cash / Bank Book',
        'reports.view' => 'View Reports',
        'reports.full' => 'View Full Financial Reports',
        'approvals.view' => 'View Approval Dashboard',
        'approvals.manage' => 'Approve / Reject Vouchers',
        'audit-trail.view' => 'View Audit Trail',
        'users.view' => 'View Users & Roles',
        'users.manage' => 'Manage Users & Roles',
        'roles.manage' => 'Manage Role Permissions',
        'inventory.view' => 'View Inventory Module',
        'inventory.manage' => 'Manage Inventory Module',
        'support.view' => 'View Support Configuration',
    ],

    'role_permissions' => [
        'Super Admin' => ['*'],
        'Admin' => ['*'],
        'Company Admin' => ['*'],
        'Finance Manager' => [
            'dashboard.view', 'company.view', 'company.manage', 'master-data.view', 'master-data.manage',
            'chart-of-accounts.view', 'chart-of-accounts.manage', 'cash-bank.view', 'cash-bank.manage',
            'parties.view', 'parties.manage', 'transaction-heads.view', 'transaction-heads.manage',
            'ledger-mapping.view', 'ledger-mapping.manage', 'opening-balances.view', 'opening-balances.manage',
            'voucher-numbering.view', 'voucher-numbering.manage', 'transactions.view', 'transactions.create',
            'transactions.edit', 'transactions.payment.create', 'transactions.receipt.create', 'transactions.journal.create',
            'transactions.sales.create', 'transactions.purchase.create', 'transactions.reverse', 'sales-invoices.view',
            'sales-invoices.manage', 'purchase-bills.view', 'purchase-bills.manage', 'customer-ledgers.view',
            'supplier-ledgers.view', 'cash-bank-book.view', 'reports.view', 'reports.full', 'approvals.view',
            'approvals.manage', 'audit-trail.view',
            'due-management.view',
            'due-management.manage',
            'advance-management.view',
            'advance-management.manage',
            'ledger-report.view',
        ],
        'Approver' => [
            'dashboard.view', 'transactions.view', 'approvals.view', 'approvals.manage', 'audit-trail.view',
            'reports.view', 'customer-ledgers.view', 'supplier-ledgers.view', 'cash-bank-book.view',
            'due-management.view',
            'advance-management.view',
            'ledger-report.view',
        ],
        'Accountant' => [
            'dashboard.view', 'chart-of-accounts.view', 'chart-of-accounts.manage', 'cash-bank.view', 'cash-bank.manage',
            'parties.view', 'parties.manage', 'transaction-heads.view', 'ledger-mapping.view', 'opening-balances.view',
            'opening-balances.manage', 'voucher-numbering.view', 'transactions.view', 'transactions.create',
            'transactions.edit', 'transactions.payment.create', 'transactions.receipt.create', 'transactions.journal.create',
            'transactions.sales.create', 'transactions.purchase.create', 'sales-invoices.view', 'sales-invoices.manage',
            'purchase-bills.view', 'purchase-bills.manage', 'customer-ledgers.view', 'supplier-ledgers.view',
            'cash-bank-book.view', 'reports.view', 'audit-trail.view',
            'due-management.view',
            'due-management.manage',
            'advance-management.view',
            'advance-management.manage',
            'ledger-report.view',
        ],
        'Cashier' => [
            'dashboard.view', 'cash-bank.view', 'transactions.view', 'transactions.create',
            'transactions.payment.create', 'transactions.receipt.create', 'cash-bank-book.view', 'reports.view',
            'due-management.view',
            'due-management.manage',
            'advance-management.view',
            'advance-management.manage',
            'ledger-report.view',
        ],
        'Sales User' => [
            'dashboard.view', 'parties.view', 'transactions.view', 'transactions.create', 'transactions.receipt.create',
            'transactions.sales.create', 'sales-invoices.view', 'sales-invoices.manage', 'customer-ledgers.view',
            'cash-bank-book.view', 'reports.view',
            'due-management.view',
            'due-management.manage',
            'advance-management.view',
            'advance-management.manage',
            'ledger-report.view',
        ],
        'Purchase User' => [
            'dashboard.view', 'parties.view', 'transactions.view', 'transactions.create', 'transactions.payment.create',
            'transactions.purchase.create', 'purchase-bills.view', 'purchase-bills.manage', 'supplier-ledgers.view',
            'cash-bank-book.view', 'reports.view',
            'due-management.view',
            'due-management.manage',
            'advance-management.view',
            'advance-management.manage',
            'ledger-report.view',
        ],
        'Inventory / Store User' => [
            'dashboard.view', 'inventory.view', 'inventory.manage', 'reports.view',
        ],
        'Branch User' => [
            'dashboard.view', 'transactions.view', 'transactions.create', 'transactions.draft', 'parties.view',
            'cash-bank.view', 'customer-ledgers.view', 'supplier-ledgers.view', 'cash-bank-book.view', 'reports.view',
            'due-management.view',
            'due-management.manage',
            'advance-management.view',
            'advance-management.manage',
            'ledger-report.view',
        ],
        'Data Entry Operator' => [
            'dashboard.view', 'transactions.view', 'transactions.draft', 'parties.view',
        ],
        'Auditor' => [
            'dashboard.view', 'company.view', 'master-data.view', 'chart-of-accounts.view', 'cash-bank.view',
            'parties.view', 'transaction-heads.view', 'ledger-mapping.view', 'opening-balances.view',
            'voucher-numbering.view', 'transactions.view', 'sales-invoices.view', 'purchase-bills.view',
            'customer-ledgers.view', 'supplier-ledgers.view', 'cash-bank-book.view', 'reports.view', 'reports.full',
            'audit-trail.view',
            'due-management.view',
            'advance-management.view',
            'ledger-report.view',
        ],
        'Management Viewer / Report Viewer' => [
            'dashboard.view', 'company.view', 'transactions.view', 'customer-ledgers.view', 'supplier-ledgers.view',
            'cash-bank-book.view', 'reports.view', 'reports.full',
            'due-management.view',
            'advance-management.view',
            'ledger-report.view',
        ],
        'Viewer' => [
            'dashboard.view', 'company.view', 'chart-of-accounts.view', 'cash-bank.view', 'parties.view',
            'transaction-heads.view', 'ledger-mapping.view', 'opening-balances.view', 'voucher-numbering.view',
            'transactions.view', 'sales-invoices.view', 'purchase-bills.view', 'customer-ledgers.view',
            'supplier-ledgers.view', 'cash-bank-book.view', 'reports.view',
            'due-management.view',
            'advance-management.view',
            'ledger-report.view',
        ],
        'Support Admin' => [
            'dashboard.view', 'company.view', 'master-data.view', 'chart-of-accounts.view', 'cash-bank.view',
            'parties.view', 'transaction-heads.view', 'ledger-mapping.view', 'opening-balances.view',
            'voucher-numbering.view', 'transactions.view', 'reports.view', 'users.view', 'support.view',
            'due-management.view',
            'advance-management.view',
            'ledger-report.view',
        ],
    ],

    'route_permissions' => [
        'dashboard' => ['dashboard.view'],
        'setup.company' => ['company.view'],
        'setup.master-data' => ['master-data.view'],
        'setup.master-data.business-types' => ['master-data.view'],
        'setup.master-data.currencies' => ['master-data.view'],
        'setup.master-data.settlement-types' => ['master-data.view'],
        'setup.master-data.party-types' => ['master-data.view'],
        'setup.master-data.financial-years' => ['master-data.view'],
        'setup.chart-of-accounts' => ['chart-of-accounts.view'],
        'setup.cash-bank-accounts' => ['cash-bank.view'],
        'setup.parties' => ['parties.view'],
        'setup.transaction-heads' => ['transaction-heads.view'],
        'setup.accounting-rules-setup' => ['ledger-mapping.view'],
        'setup.ledger-mapping' => ['ledger-mapping.view'],
        'setup.opening-balances' => ['opening-balances.view'],
        'setup.voucher-numbering' => ['voucher-numbering.view'],
        'transactions.create' => ['transactions.view', 'transactions.create', 'transactions.draft'],
        'due-management.index' => ['due-management.view', 'customer-ledgers.view', 'supplier-ledgers.view', 'reports.view'],
        'advance-management.index' => ['advance-management.view', 'reports.view', 'customer-ledgers.view', 'supplier-ledgers.view'],
        'ledger-report.index' => ['ledger-report.view', 'reports.view', 'customer-ledgers.view', 'supplier-ledgers.view'],
        'accounting-reports.index' => ['reports.view', 'cash-bank-book.view', 'transactions.view'],
        'accounting-reports.transactions.index' => ['transactions.view', 'reports.view'],
        'accounting-reports.transactions.export' => ['transactions.view', 'reports.view'],
        'accounting-reports.transactions.show' => ['transactions.view', 'reports.view'],
        'accounting-reports.transactions.reverse' => ['transactions.reverse'],
        'accounting-reports.cash-bank-book.index' => ['cash-bank-book.view', 'reports.view'],
        'accounting-reports.cash-bank-book.export' => ['cash-bank-book.view', 'reports.view'],
        'settings.users-roles' => ['users.view'],
    ],

    'manage_permissions' => [
        'setup.company' => 'company.manage',
        'setup.master-data' => 'master-data.manage',
        'setup.master-data.business-types' => 'master-data.manage',
        'setup.master-data.currencies' => 'master-data.manage',
        'setup.master-data.settlement-types' => 'master-data.manage',
        'setup.master-data.party-types' => 'master-data.manage',
        'setup.master-data.financial-years' => 'master-data.manage',
        'setup.chart-of-accounts' => 'chart-of-accounts.manage',
        'setup.cash-bank-accounts' => 'cash-bank.manage',
        'setup.parties' => 'parties.manage',
        'setup.transaction-heads' => 'transaction-heads.manage',
        'setup.accounting-rules-setup' => 'ledger-mapping.manage',
        'setup.ledger-mapping' => 'ledger-mapping.manage',
        'setup.opening-balances' => 'opening-balances.manage',
        'setup.voucher-numbering' => 'voucher-numbering.manage',
        'transactions.create' => ['transactions.create', 'transactions.draft'],
        'due-management.index' => ['due-management.manage', 'transactions.create'],
        'advance-management.index' => ['advance-management.manage', 'transactions.create'],
        'settings.users-roles' => 'users.manage',
    ],

    'transaction_type_permissions' => [
        'Payment' => 'transactions.payment.create',
        'Receipt' => 'transactions.receipt.create',
        'Journal' => 'transactions.journal.create',
        'Adjustment' => 'transactions.journal.create',
        'Due' => 'transactions.journal.create',
    ],

    'matrix' => [
        ['feature' => 'Company Setup', 'Super Admin' => 'Full', 'Company Admin' => 'Full', 'Finance Manager' => 'View/Edit', 'Accountant' => 'No', 'Cashier' => 'No', 'Sales User' => 'No', 'Purchase User' => 'No', 'Auditor' => 'View', 'Viewer' => 'View'],
        ['feature' => 'Chart of Accounts', 'Super Admin' => 'Full', 'Company Admin' => 'Full', 'Finance Manager' => 'Full', 'Accountant' => 'Create/Edit', 'Cashier' => 'No', 'Sales User' => 'No', 'Purchase User' => 'No', 'Auditor' => 'View', 'Viewer' => 'View'],
        ['feature' => 'Accounting Rule Setup', 'Super Admin' => 'Full', 'Company Admin' => 'Full', 'Finance Manager' => 'Full', 'Accountant' => 'Limited/View', 'Cashier' => 'No', 'Sales User' => 'No', 'Purchase User' => 'No', 'Auditor' => 'View', 'Viewer' => 'View'],
        ['feature' => 'Voucher Entry', 'Super Admin' => 'Full', 'Admin' => 'Full', 'Company Admin' => 'Full', 'Finance Manager' => 'Full', 'Approver' => 'View/Approve', 'Accountant' => 'Create/Edit', 'Cashier' => 'Cash/Bank only', 'Sales User' => 'Sales related', 'Purchase User' => 'Purchase related', 'Inventory / Store User' => 'No', 'Branch User' => 'Limited', 'Data Entry Operator' => 'Draft Only', 'Auditor' => 'View', 'Management Viewer / Report Viewer' => 'View', 'Viewer' => 'View', 'Support Admin' => 'View'],
        ['feature' => 'Voucher Approval', 'Super Admin' => 'Full', 'Company Admin' => 'Full', 'Finance Manager' => 'Full', 'Accountant' => 'No/Optional', 'Cashier' => 'No', 'Sales User' => 'No', 'Purchase User' => 'No', 'Auditor' => 'No', 'Viewer' => 'No'],
        ['feature' => 'Sales Invoice', 'Super Admin' => 'Full', 'Company Admin' => 'Full', 'Finance Manager' => 'Full', 'Accountant' => 'Full', 'Cashier' => 'View', 'Sales User' => 'Create/Edit', 'Purchase User' => 'No', 'Auditor' => 'View', 'Viewer' => 'View'],
        ['feature' => 'Purchase Bill', 'Super Admin' => 'Full', 'Company Admin' => 'Full', 'Finance Manager' => 'Full', 'Accountant' => 'Full', 'Cashier' => 'No', 'Sales User' => 'No', 'Purchase User' => 'Create/Edit', 'Auditor' => 'View', 'Viewer' => 'View'],
        ['feature' => 'Receipt Entry', 'Super Admin' => 'Full', 'Admin' => 'Full', 'Company Admin' => 'Full', 'Finance Manager' => 'Full', 'Approver' => 'View/Approve', 'Accountant' => 'Full', 'Cashier' => 'Create', 'Sales User' => 'Create', 'Purchase User' => 'No', 'Inventory / Store User' => 'No', 'Branch User' => 'Limited', 'Data Entry Operator' => 'Draft Only', 'Auditor' => 'View', 'Management Viewer / Report Viewer' => 'View', 'Viewer' => 'View', 'Support Admin' => 'View'],
        ['feature' => 'Payment Entry', 'Super Admin' => 'Full', 'Admin' => 'Full', 'Company Admin' => 'Full', 'Finance Manager' => 'Full', 'Approver' => 'View/Approve', 'Accountant' => 'Full', 'Cashier' => 'Create', 'Sales User' => 'No', 'Purchase User' => 'Create', 'Inventory / Store User' => 'No', 'Branch User' => 'Limited', 'Data Entry Operator' => 'Draft Only', 'Auditor' => 'View', 'Management Viewer / Report Viewer' => 'View', 'Viewer' => 'View', 'Support Admin' => 'View'],
        ['feature' => 'Journal Entry', 'Super Admin' => 'Full', 'Admin' => 'Full', 'Company Admin' => 'Full', 'Finance Manager' => 'Full', 'Approver' => 'View/Approve', 'Accountant' => 'Create/Edit', 'Cashier' => 'No', 'Sales User' => 'No', 'Purchase User' => 'No', 'Inventory / Store User' => 'No', 'Branch User' => 'Limited', 'Data Entry Operator' => 'Draft Only', 'Auditor' => 'View', 'Management Viewer / Report Viewer' => 'View', 'Viewer' => 'View', 'Support Admin' => 'View'],
        ['feature' => 'Customer Ledger', 'Super Admin' => 'Full', 'Company Admin' => 'Full', 'Finance Manager' => 'Full', 'Accountant' => 'Full', 'Cashier' => 'View', 'Sales User' => 'Full', 'Purchase User' => 'No', 'Auditor' => 'View', 'Viewer' => 'View'],
        ['feature' => 'Supplier Ledger', 'Super Admin' => 'Full', 'Company Admin' => 'Full', 'Finance Manager' => 'Full', 'Accountant' => 'Full', 'Cashier' => 'No', 'Sales User' => 'No', 'Purchase User' => 'Full', 'Auditor' => 'View', 'Viewer' => 'View'],
        ['feature' => 'Cash/Bank Book', 'Super Admin' => 'Full', 'Company Admin' => 'Full', 'Finance Manager' => 'Full', 'Accountant' => 'Full', 'Cashier' => 'Full', 'Sales User' => 'Limited', 'Purchase User' => 'Limited', 'Auditor' => 'View', 'Viewer' => 'View'],
        ['feature' => 'Reports', 'Super Admin' => 'Full', 'Company Admin' => 'Full', 'Finance Manager' => 'Full', 'Accountant' => 'View', 'Cashier' => 'Limited', 'Sales User' => 'Limited', 'Purchase User' => 'Limited', 'Auditor' => 'Full View', 'Viewer' => 'View'],
        ['feature' => 'User Management', 'Super Admin' => 'Full', 'Company Admin' => 'Full', 'Finance Manager' => 'No/Optional', 'Accountant' => 'No', 'Cashier' => 'No', 'Sales User' => 'No', 'Purchase User' => 'No', 'Auditor' => 'No', 'Viewer' => 'No'],
        ['feature' => 'Data Entry Draft Control', 'Super Admin' => 'Full', 'Admin' => 'Full', 'Company Admin' => 'Full', 'Finance Manager' => 'Full', 'Approver' => 'No', 'Accountant' => 'Full', 'Cashier' => 'No', 'Sales User' => 'No', 'Purchase User' => 'No', 'Inventory / Store User' => 'No', 'Branch User' => 'Limited Draft', 'Data Entry Operator' => 'Draft Only', 'Auditor' => 'View', 'Management Viewer / Report Viewer' => 'View', 'Viewer' => 'View', 'Support Admin' => 'View'],
        ['feature' => 'Delete / Reverse Transaction', 'Super Admin' => 'Full', 'Company Admin' => 'Controlled', 'Finance Manager' => 'Controlled', 'Accountant' => 'No/Optional', 'Cashier' => 'No', 'Sales User' => 'No', 'Purchase User' => 'No', 'Auditor' => 'No', 'Viewer' => 'No'],
        ['feature' => 'Audit Trail', 'Super Admin' => 'Full', 'Company Admin' => 'Full', 'Finance Manager' => 'Full', 'Accountant' => 'View own activity', 'Cashier' => 'No', 'Sales User' => 'No', 'Purchase User' => 'No', 'Auditor' => 'Full View', 'Viewer' => 'No/Optional'],
    ],
];
