<?php

return [
    'defaults' => [
        'meta' => [
            'title' => 'HisebGhor | সহজ হিসাব সফটওয়্যার',
            'description' => 'HisebGhor is a simple accounting system for SMEs in Bangladesh.',
            'default_lang' => 'bn',
        ],
        'theme' => [
            'green' => '#00a86b',
            'green_dark' => '#087a52',
            'green_soft' => '#e9fff5',
            'blue' => '#2563eb',
            'gold' => '#f59e0b',
            'ink' => '#101828',
            'muted' => '#667085',
            'bg' => '#f8fafc',
        ],
        'brand' => [
            'name' => 'HisebGhor',
            'logo_text' => 'হি',
            'logo' => ['path' => 'images/landing/hisebghor-logo.png', 'name' => 'HisebGhor'],
            'tagline' => ['bn' => 'সহজ হিসাব সফটওয়্যার', 'en' => 'Simple Accounting Software'],
        ],
        'nav_links' => [
            ['label' => ['bn' => 'কেন', 'en' => 'Why'], 'href' => '#why'],
            ['label' => ['bn' => 'ফিচার', 'en' => 'Features'], 'href' => '#features'],
            ['label' => ['bn' => 'কার জন্য', 'en' => 'For Whom'], 'href' => '#for'],
            ['label' => ['bn' => 'প্যাকেজ', 'en' => 'Pricing'], 'href' => '#pricing'],
            ['label' => ['bn' => 'প্রশ্ন', 'en' => 'FAQ'], 'href' => '#faq'],
        ],
        'cta' => [
            'primary' => ['label' => ['bn' => 'ডেমো চাই', 'en' => 'Demo Chat'], 'href' => '#contact'],
            'secondary' => ['label' => ['bn' => 'লগইন', 'en' => 'Login'], 'href' => '/login'],
        ],
        'hero' => [
            'enabled' => true,
            'eyebrow' => ['bn' => '🇧🇩 বাংলাদেশের SME ব্যবসার জন্য তৈরি', 'en' => '🇧🇩 Built for SMEs in Bangladesh'],
            'title' => ['bn' => 'হিসাব রাখুন সহজে। ব্যবসা বুঝুন পরিষ্কারভাবে।', 'en' => 'Track accounts easily. Understand your business clearly.'],
            'highlight' => ['bn' => '', 'en' => ''],
            'subtitle' => [
                'bn' => 'HisebGhor হলো ছোট ও মাঝারি ব্যবসার জন্য সহজ হিসাব সফটওয়্যার। দৈনিক লেনদেন, বাকি, অগ্রিম, নগদ/ব্যাংক, ভাউচার এবং রিপোর্ট—সব এক জায়গায়। জটিল হিসাব না। সহজ কাজ। পরিষ্কার ফলাফল।',
                'en' => 'HisebGhor is a simple accounting system for small and medium businesses. Daily transactions, due, advance, cash/bank, voucher and reports—everything in one place. No complex accounting. Simple work. Clear result.',
            ],
            'buttons' => [
                ['style' => 'primary', 'label' => ['bn' => 'ফ্রি ডেমো বুক করুন', 'en' => 'Book Free Demo'], 'href' => '#contact'],
                ['style' => 'outline', 'label' => ['bn' => 'ফিচার দেখুন', 'en' => 'Explore Features'], 'href' => '#features'],
            ],
            'dashboard' => [
                'title' => ['bn' => 'আজকের হিসাব', 'en' => "Today's Accounts"],
                'subtitle' => ['bn' => 'লাইভ ড্যাশবোর্ড', 'en' => 'Live dashboard'],
                'chip' => ['bn' => 'সক্রিয়', 'en' => 'Active'],
                'image' => ['path' => 'images/landing/hero-dashboard.png', 'name' => 'HisebGhor dashboard preview'],
                'stats' => [
                    ['label' => ['bn' => 'নগদ', 'en' => 'Cash'], 'value' => '৳ ১,৫০,০০০'],
                    ['label' => ['bn' => 'ব্যাংক', 'en' => 'Bank'], 'value' => '৳ ৮,৫০,০০০'],
                    ['label' => ['bn' => 'বাকি', 'en' => 'Due'], 'value' => '৳ ১,২৫,০০০'],
                ],
                'rows' => [
                    ['name' => ['bn' => 'বেতন প্রদান', 'en' => 'Salary Payment'], 'debit' => '৳ ১০,০০০', 'credit' => '৳ ১০,০০০'],
                    ['name' => ['bn' => 'ভাড়া আয়', 'en' => 'Rent Income'], 'debit' => '৳ ৫০,০০০', 'credit' => '৳ ৫০,০০০'],
                    ['name' => ['bn' => 'সাপ্লায়ার বাকি', 'en' => 'Supplier Due'], 'debit' => '৳ ২৫,০০০', 'credit' => '৳ ২৫,০০০'],
                ],
            ],
        ],
        'trust_items' => [
            ['bn' => 'SME-friendly', 'en' => 'SME-friendly'],
            ['bn' => 'বাংলা + English', 'en' => 'Bangla + English'],
            ['bn' => 'সহজ রিপোর্ট', 'en' => 'Easy reports'],
        ],
        'why' => [
            'enabled' => true,
            'mini' => ['bn' => 'কেন HisebGhor', 'en' => 'Why HisebGhor'],
            'title' => ['bn' => 'অনেক SME হিসাব রাখে, কিন্তু বুঝতে পারে না আসল অবস্থা।', 'en' => 'Many SMEs keep accounts, but cannot see the real picture.'],
            'subtitle' => ['bn' => 'খাতা, Excel, WhatsApp নোট, ব্যাংক SMS—সব জায়গায় হিসাব ছড়িয়ে থাকে। HisebGhor এগুলোকে সহজভাবে এক জায়গায় আনে।', 'en' => 'Notebook, Excel, WhatsApp notes, bank SMS—business records stay scattered. HisebGhor brings them into one simple place.'],
        ],
        'why_cards' => [
            ['icon' => '৳', 'title' => ['bn' => 'সহজ লেনদেন', 'en' => 'Easy Transactions'], 'body' => ['bn' => 'শুধু হেড, ব্যক্তি/পার্টি, পরিমাণ, নগদ/ব্যাংক/বাকি/অগ্রিম নির্বাচন করুন। লেজার সিস্টেম তৈরি করবে।', 'en' => 'Enter head, party, amount, and cash/bank/due/advance. The system prepares the ledger.']],
            ['icon' => '📌', 'title' => ['bn' => 'বাকি ও অগ্রিম ট্র্যাকিং', 'en' => 'Due & Advance Tracking'], 'body' => ['bn' => 'কে টাকা পাবে, কার কাছ থেকে টাকা আসবে, কোথায় অগ্রিম আছে—পরিষ্কারভাবে দেখা যাবে।', 'en' => 'See who needs to be paid, who needs to pay you, and where advance balance exists.']],
            ['icon' => '📊', 'title' => ['bn' => 'রিপোর্ট এক ক্লিকে', 'en' => 'Reports in One Click'], 'body' => ['bn' => 'Cash/Bank book, ledger report, transaction list, voucher trail—সব রিপোর্ট সহজ ও পরিষ্কার।', 'en' => 'Cash/bank book, ledger report, transaction list, voucher trail—clear and easy reports.']],
        ],
        'features' => [
            'enabled' => true,
            'mini' => ['bn' => 'স্ক্রিনশট ও ফিচার', 'en' => 'Screenshots & Features'],
            'title' => ['bn' => 'স্ক্রিনগুলো সহজ। কাজের জায়গা পরিষ্কার।', 'en' => 'Simple screens. Clear working space.'],
            'subtitle' => ['bn' => 'ব্যবহারকারী যেন হিসাববিদ না হয়েও লেনদেন করতে পারে—এই ভাবনা থেকে UI তৈরি।', 'en' => 'The UI is designed so a user can enter transactions even without being an accountant.'],
        ],
        'screens' => [
            ['image' => ['path' => 'images/landing/feature-screen.png', 'name' => 'HisebGhor feature preview'], 'badges' => [['bn' => 'Auto Ledger Preview', 'en' => 'Auto Ledger Preview'], ['bn' => 'Cash / Bank / Due', 'en' => 'Cash / Bank / Due']], 'title' => ['bn' => 'Daily Transaction Entry', 'en' => 'Daily Transaction Entry'], 'body' => ['bn' => 'লেনদেন এন্ট্রি করার সময়ই ডেবিট-ক্রেডিট দেখা যাবে। ভুল কমবে।', 'en' => 'Debit-credit preview appears while entering transaction. It reduces mistakes.']],
            ['image' => ['path' => 'images/landing/feature-screen.png', 'name' => 'HisebGhor feature preview'], 'badges' => [['bn' => 'Due Payable', 'en' => 'Due Payable'], ['bn' => 'Due Receivable', 'en' => 'Due Receivable']], 'title' => ['bn' => 'Due Management', 'en' => 'Due Management'], 'body' => ['bn' => 'বাকি তৈরি, আংশিক পেমেন্ট, কালেকশন এবং ব্যালেন্স—সব ট্র্যাক হবে।', 'en' => 'Create due, partial payment, collection and balance tracking in one screen.']],
            ['image' => ['path' => 'images/landing/feature-screen.png', 'name' => 'HisebGhor feature preview'], 'badges' => [['bn' => 'Advance Paid', 'en' => 'Advance Paid'], ['bn' => 'Advance Received', 'en' => 'Advance Received']], 'title' => ['bn' => 'Advance Tracking', 'en' => 'Advance Tracking'], 'body' => ['bn' => 'সাপ্লায়ার, কর্মী বা কাস্টমারের অগ্রিম সহজে দেখা ও অ্যাডজাস্ট করা যাবে।', 'en' => 'Track and adjust supplier, employee or customer advances easily.']],
            ['image' => ['path' => 'images/landing/feature-screen.png', 'name' => 'HisebGhor feature preview'], 'badges' => [['bn' => 'Ledger Report', 'en' => 'Ledger Report'], ['bn' => 'Cash/Bank Book', 'en' => 'Cash/Bank Book']], 'title' => ['bn' => 'Reports', 'en' => 'Reports'], 'body' => ['bn' => 'লেনদেন, লেজার, ভাউচার ও cash/bank movement দ্রুত দেখা যাবে।', 'en' => 'View transactions, ledger, voucher and cash/bank movement quickly.']],
        ],
        'audience' => [
            'enabled' => true,
            'icon' => '🏪',
            'title' => ['bn' => 'আপনার ব্যবসার জন্য HisebGhor কি উপযোগী?', 'en' => 'Is HisebGhor suitable for your business?'],
            'body' => ['bn' => 'HisebGhor মূলত ছোট ও মাঝারি ব্যবসার জন্য ভালো, যেখানে হিসাব রাখার দরকার আছে কিন্তু বড় ERP দরকার নেই।', 'en' => 'HisebGhor is designed for small and medium businesses that need dependable accounting without a large ERP.'],
        ],
        'audiences' => [
            ['title' => ['bn' => 'Trading business', 'en' => 'Trading business'], 'body' => ['bn' => 'Regular sale, purchase, customer due এবং supplier payment tracking-এর জন্য।', 'en' => 'For regular sales, purchases, customer dues, and supplier payment tracking.']],
            ['title' => ['bn' => 'Service business', 'en' => 'Service business'], 'body' => ['bn' => 'Client billing, collection, expense এবং project-wise হিসাব রাখার জন্য।', 'en' => 'For client billing, collection, expenses, and project-wise accounting.']],
            ['title' => ['bn' => 'Small factory বা production business', 'en' => 'Small factory or production business'], 'body' => ['bn' => 'Raw material purchase, worker payment, sale এবং operating expense track করার জন্য।', 'en' => 'For raw-material purchases, worker payments, sales, and operating expenses.']],
            ['title' => ['bn' => 'Farming বা agro business', 'en' => 'Farming or agro business'], 'body' => ['bn' => 'Feed, medicine, labor, sale, party due এবং farm-wise expense tracking-এর জন্য।', 'en' => 'For feed, medicine, labor, sales, party dues, and farm-wise expense tracking.']],
            ['title' => ['bn' => 'Distributor বা dealer business', 'en' => 'Distributor or dealer business'], 'body' => ['bn' => 'Customer-wise due, supplier payment, cash/bank position এবং daily sales tracking-এর জন্য।', 'en' => 'For customer-wise dues, supplier payments, cash/bank position, and daily sales tracking.']],
        ],
        'pricing' => [
            'enabled' => true,
            'mini' => ['bn' => 'Implementation Packages', 'en' => 'Implementation Packages'],
            'title' => ['bn' => 'আপনার ব্যবসার ধরন অনুযায়ী প্যাকেজ নির্বাচন করুন।', 'en' => 'Choose a package based on your business type.'],
            'subtitle' => [
                'bn' => 'HisebGhor এখন single customer implementation basis-এ সেবা হচ্ছে। আপনার ব্যবসার জন্য আলাদা system setup করা হবে। Cloud অথবা On-Premise—দুই ধরনের deployment করা যায়।',
                'en' => 'HisebGhor is currently provided on a single-customer implementation basis. A separate system will be configured for your business, with either Cloud or On-Premise deployment.',
            ],
            'notes_title' => ['bn' => 'Important Notes', 'en' => 'Important Notes'],
        ],
        'packages' => [
            [
                'icon' => 'cloud',
                'name' => ['bn' => 'Basic Cloud', 'en' => 'Basic Cloud'],
                'tag' => ['bn' => 'Starter', 'en' => 'Starter'],
                'body' => ['bn' => 'ছোট দোকান, ছোট trading business, ছোট service business', 'en' => 'Small shops, small trading businesses, and small service businesses.'],
                'fees' => [
                    'installation' => [
                        'label' => ['bn' => 'Installation Fee', 'en' => 'Installation Fee'],
                        'amount' => '৳35,000 – ৳50,000',
                        'note' => ['bn' => 'One-time', 'en' => 'One-time'],
                    ],
                    'maintenance' => [
                        'label' => ['bn' => 'Maintenance Fee', 'en' => 'Maintenance Fee'],
                        'amount' => '৳3,000',
                        'note' => ['bn' => '/month', 'en' => '/month'],
                    ],
                    'hosting' => [
                        'label' => ['bn' => 'Server Hosting', 'en' => 'Server Hosting'],
                        'amount' => 'Actual cost',
                        'note' => ['bn' => '/month', 'en' => '/month'],
                    ],
                ],
                'features' => [
                    ['bn' => 'Basic accounting setup', 'en' => 'Basic accounting setup'],
                    ['bn' => 'Chart of Accounts setup', 'en' => 'Chart of Accounts setup'],
                    ['bn' => 'Customer / Supplier / Party setup', 'en' => 'Customer / Supplier / Party setup'],
                    ['bn' => 'Cash & bank account setup', 'en' => 'Cash & bank account setup'],
                    ['bn' => 'Daily transaction entry', 'en' => 'Daily transaction entry'],
                    ['bn' => 'Customer due tracking', 'en' => 'Customer due tracking'],
                    ['bn' => 'Supplier payable tracking', 'en' => 'Supplier payable tracking'],
                    ['bn' => 'Basic reports', 'en' => 'Basic reports'],
                    ['bn' => 'User setup up to 3 users', 'en' => 'User setup up to 3 users'],
                    ['bn' => 'Basic training', 'en' => 'Basic training'],
                    ['bn' => '15 days post-live support', 'en' => '15 days post-live support'],
                ],
            ],
            [
                'icon' => 'building',
                'name' => ['bn' => 'Standard Cloud', 'en' => 'Standard Cloud'],
                'tag' => ['bn' => 'Recommended', 'en' => 'Recommended'],
                'body' => ['bn' => 'Growing SME, multiple users, regular due/payment tracking প্রয়োজন এমন business', 'en' => 'Growing SMEs that need multiple users and regular due/payment tracking.'],
                'fees' => [
                    'installation' => [
                        'label' => ['bn' => 'Installation Fee', 'en' => 'Installation Fee'],
                        'amount' => '৳70,000 – ৳95,000',
                        'note' => ['bn' => 'One-time', 'en' => 'One-time'],
                    ],
                    'maintenance' => [
                        'label' => ['bn' => 'Maintenance Fee', 'en' => 'Maintenance Fee'],
                        'amount' => '৳5,000',
                        'note' => ['bn' => '/month', 'en' => '/month'],
                    ],
                    'hosting' => [
                        'label' => ['bn' => 'Server Hosting', 'en' => 'Server Hosting'],
                        'amount' => 'Actual cost',
                        'note' => ['bn' => '/month', 'en' => '/month'],
                    ],
                ],
                'features' => [
                    ['bn' => 'Full accounting configuration', 'en' => 'Full accounting configuration'],
                    ['bn' => 'Chart of Accounts customization', 'en' => 'Chart of Accounts customization'],
                    ['bn' => 'Transaction heads setup', 'en' => 'Transaction heads setup'],
                    ['bn' => 'Accounting rules setup', 'en' => 'Accounting rules setup'],
                    ['bn' => 'Customer, supplier, worker, owner party setup', 'en' => 'Customer, supplier, worker, owner party setup'],
                    ['bn' => 'Cash, bank and mobile banking account setup', 'en' => 'Cash, bank and mobile banking account setup'],
                    ['bn' => 'Sales, purchase, expense, payment and collection flow', 'en' => 'Sales, purchase, expense, payment and collection flow'],
                    ['bn' => 'Partial payment handling', 'en' => 'Partial payment handling'],
                    ['bn' => 'Party balance report', 'en' => 'Party balance report'],
                    ['bn' => 'Account balance report', 'en' => 'Account balance report'],
                    ['bn' => 'Income–expense summary', 'en' => 'Income–expense summary'],
                    ['bn' => 'User role and permission setup', 'en' => 'User role and permission setup'],
                    ['bn' => 'Data import support', 'en' => 'Data import support'],
                    ['bn' => 'Training for owner/accountant/user', 'en' => 'Training for owner/accountant/user'],
                    ['bn' => '30 days post-live support', 'en' => '30 days post-live support'],
                ],
            ],
            [
                'icon' => 'server',
                'name' => ['bn' => 'On-Premise / Private Deployment', 'en' => 'On-Premise / Private Deployment'],
                'tag' => ['bn' => 'Setup', 'en' => 'Setup'],
                'body' => ['bn' => 'যেসব business নিজের server, private hosting অথবা internal control চায়', 'en' => 'Businesses that want their own server, private hosting, or internal control.'],
                'fees' => [
                    'installation' => [
                        'label' => ['bn' => 'Installation Fee', 'en' => 'Installation Fee'],
                        'amount' => '৳120,000 – ৳180,000',
                        'note' => ['bn' => 'One-time', 'en' => 'One-time'],
                    ],
                    'maintenance' => [
                        'label' => ['bn' => 'Maintenance Fee', 'en' => 'Maintenance Fee'],
                        'amount' => '৳8,000 – ৳12,000',
                        'note' => ['bn' => '/month', 'en' => '/month'],
                    ],
                    'hosting' => [
                        'label' => ['bn' => 'Server Hosting', 'en' => 'Server Hosting'],
                        'amount' => 'Actual cost',
                        'note' => ['bn' => '/month', 'en' => '/month'],
                    ],
                ],
                'features' => [
                    ['bn' => 'Dedicated installation', 'en' => 'Dedicated installation'],
                    ['bn' => 'Business-wise accounting setup', 'en' => 'Business-wise accounting setup'],
                    ['bn' => 'Full configuration and deployment', 'en' => 'Full configuration and deployment'],
                    ['bn' => 'On-premise or private cloud setup', 'en' => 'On-premise or private cloud setup'],
                    ['bn' => 'User and access control', 'en' => 'User and access control'],
                    ['bn' => 'Backup process guidance', 'en' => 'Backup process guidance'],
                    ['bn' => 'Data migration support', 'en' => 'Data migration support'],
                    ['bn' => 'Report configuration', 'en' => 'Report configuration'],
                    ['bn' => 'Training and handover', 'en' => 'Training and handover'],
                    ['bn' => 'Priority support', 'en' => 'Priority support'],
                    ['bn' => '45 days post-live support', 'en' => '45 days post-live support'],
                ],
            ],
        ],
        'pricing_notes' => [
            [
                'icon' => 'tag',
                'title' => ['bn' => 'Pricing Note', 'en' => 'Pricing Note'],
                'body' => [
                    'bn' => 'উপরের pricing indicative। Final cost নির্ভর করবে business process, number of users, data migration, report customization এবং deployment type-এর উপর।',
                    'en' => 'The pricing above is indicative. Final cost depends on the business process, number of users, data migration, report customization, and deployment type.',
                ],
            ],
            [
                'icon' => 'server',
                'title' => ['bn' => 'Server Note', 'en' => 'Server Note'],
                'body' => [
                    'bn' => 'Server cost actual bill অনুযায়ী client বহন করবে। প্রয়োজনে DigitalOcean, AWS, local VPS বা client’s own server ব্যবহার করা যাবে।',
                    'en' => 'The client will bear the actual server bill. DigitalOcean, AWS, a local VPS, or the client’s own server may be used.',
                ],
            ],
            [
                'icon' => 'wrench',
                'title' => ['bn' => 'Maintenance Note', 'en' => 'Maintenance Note'],
                'body' => [
                    'bn' => 'Monthly maintenance-এর মধ্যে minor support, bug fixing, basic monitoring এবং small operational assistance থাকবে। New feature বা large customization আলাদা estimate অনুযায়ী হবে।',
                    'en' => 'Monthly maintenance includes minor support, bug fixing, basic monitoring, and small operational assistance. New features or large customizations will be estimated separately.',
                ],
            ],
        ],
        'testimonials_section' => [
            'enabled' => true,
            'mini' => ['bn' => 'কাস্টমারদের কথা', 'en' => 'Testimonials'],
            'title' => ['bn' => 'যারা সহজ হিসাব চান, তাদের জন্য।', 'en' => 'For people who want simple accounting.'],
        ],
        'testimonials' => [
            ['quote' => ['bn' => 'আমাদের আগে বাকি হিসাব Excel আর খাতায় থাকত। এখন কার কাছে কত পাওনা, সহজে দেখা যায়।', 'en' => 'Earlier our dues were split between Excel and notebooks. Now we can see who owes what easily.'], 'name' => 'Rahim Traders', 'role' => ['bn' => 'SME Owner, Dhaka', 'en' => 'SME Owner, Dhaka'], 'avatar' => 'R'],
            ['quote' => ['bn' => 'Daily cash আর bank movement দ্রুত বোঝা যায়। মালিক হিসেবে এটা খুব দরকারি।', 'en' => 'Daily cash and bank movement is easier to understand. As an owner, that is very important.'], 'name' => 'ABC Services', 'role' => ['bn' => 'Service Business', 'en' => 'Service Business'], 'avatar' => 'A'],
            ['quote' => ['bn' => 'Software বড় না। কিন্তু দরকারি কাজগুলো আছে। আমাদের team সহজে ব্যবহার করতে পারে।', 'en' => 'The software is not overloaded. It has the needed features, and our team can use it easily.'], 'name' => 'M Trading', 'role' => ['bn' => 'Trading Business', 'en' => 'Trading Business'], 'avatar' => 'M'],
        ],
        'faq_section' => [
            'enabled' => true,
            'mini' => ['bn' => 'FAQ', 'en' => 'FAQ'],
            'title' => ['bn' => 'সাধারণ প্রশ্ন', 'en' => 'Common Questions'],
        ],
        'faqs' => [
            ['question' => ['bn' => 'HisebGhor কি accounting knowledge ছাড়াও ব্যবহার করা যাবে?', 'en' => 'Can HisebGhor be used without accounting knowledge?'], 'answer' => ['bn' => 'হ্যাঁ। ব্যবহারকারী transaction head, party, amount এবং cash/bank/due/advance নির্বাচন করবে। backend ledger mapping অনুযায়ী debit-credit তৈরি করবে।', 'en' => 'Yes. The user selects transaction head, party, amount and cash/bank/due/advance. The backend creates debit-credit based on ledger mapping.'], 'open' => true],
            ['question' => ['bn' => 'এটা কি ERP?', 'en' => 'Is this an ERP?'], 'answer' => ['bn' => 'না, এটি simple accounting management system। SME ব্যবসার basic accounting, due, advance, cash/bank ও রিপোর্টের জন্য তৈরি।', 'en' => 'No, it is a simple accounting management system. It is built for SME basic accounting, due, advance, cash/bank and reports.']],
            ['question' => ['bn' => 'Bangla এবং English দুই ভাষায় হবে?', 'en' => 'Will it support Bangla and English?'], 'answer' => ['bn' => 'হ্যাঁ, UI Bangla এবং English দুই ভাষাতেই করা যাবে।', 'en' => 'Yes, the UI can be provided in both Bangla and English.']],
            ['question' => ['bn' => 'কাস্টমাইজেশন করা যাবে?', 'en' => 'Can it be customized?'], 'answer' => ['bn' => 'হ্যাঁ। আপনার business process, report format, voucher format এবং approval flow অনুযায়ী কাস্টমাইজ করা যাবে।', 'en' => 'Yes. It can be customized based on your business process, report format, voucher format and approval flow.']],
        ],
        'contact' => [
            'enabled' => true,
            'title' => ['bn' => 'ডেমো দেখতে চান?', 'en' => 'Want to see a demo?'],
            'body' => ['bn' => 'আপনার ব্যবসার ধরন বলুন। আমরা দেখাব HisebGhor কীভাবে আপনার দৈনিক হিসাব, বাকি, অগ্রিম ও রিপোর্ট সহজ করতে পারে।', 'en' => 'Tell us about your business. We will show how HisebGhor can simplify your daily accounts, due, advance and reports.'],
            'phone' => '+8801742110660',
            'email' => 'aminul@itqanconsulting.com',
            'phone_note' => ['bn' => 'কল বা WhatsApp করুন', 'en' => 'Call or WhatsApp'],
            'email_note' => ['bn' => 'ইমেইল করুন', 'en' => 'Send email'],
            'form' => [
                'name' => ['bn' => 'আপনার নাম', 'en' => 'Your name'],
                'business_name' => ['bn' => 'ব্যবসার নাম', 'en' => 'Business name'],
                'mobile' => ['bn' => 'মোবাইল নম্বর', 'en' => 'Mobile number'],
                'email' => ['bn' => 'ইমেইল (ঐচ্ছিক)', 'en' => 'Email (optional)'],
                'message' => ['bn' => 'আপনার ব্যবসার হিসাব নিয়ে কী সমস্যা হচ্ছে?', 'en' => 'What problem are you facing with your business accounts?'],
                'button' => ['bn' => 'ডেমো রিকোয়েস্ট পাঠান', 'en' => 'Send Demo Request'],
                'success' => ['bn' => 'ধন্যবাদ! ডেমো রিকোয়েস্ট গ্রহণ করা হয়েছে।', 'en' => 'Thank you! Demo request received.'],
                'error' => ['bn' => 'রিকোয়েস্ট পাঠানো যায়নি। অনুগ্রহ করে আবার চেষ্টা করুন।', 'en' => 'Could not send the request. Please try again.'],
            ],
            'captcha' => [
                'enabled' => true,
                'title' => ['bn' => 'নিরাপত্তা যাচাই', 'en' => 'Security verification'],
                'instruction' => ['bn' => 'ডেমো রিকোয়েস্ট পাঠাতে নিচের সহজ হিসাবটির উত্তর দিন।', 'en' => 'Solve the simple calculation below to send your demo request.'],
                'placeholder' => ['bn' => 'উত্তর লিখুন', 'en' => 'Enter the answer'],
                'verify_button' => ['bn' => 'যাচাই করে পাঠান', 'en' => 'Verify and send'],
                'refresh_button' => ['bn' => 'নতুন প্রশ্ন', 'en' => 'New question'],
                'cancel_button' => ['bn' => 'বাতিল', 'en' => 'Cancel'],
                'loading_message' => ['bn' => 'নিরাপত্তা প্রশ্ন তৈরি হচ্ছে...', 'en' => 'Preparing the security question...'],
                'invalid_message' => ['bn' => 'উত্তরটি সঠিক নয় অথবা প্রশ্নটির সময় শেষ হয়েছে। আবার চেষ্টা করুন।', 'en' => 'The answer is incorrect or the question has expired. Please try again.'],
            ],
        ],
        'footer' => [
            'text' => ['bn' => 'HisebGhor হলো ITQAN Consulting-এর একটি উদ্যোগ।', 'en' => 'HisebGhor is an initiative of ITQAN Consulting.'],
        ],
    ],
];
